version: '3.1'
services:
  db:
    build:
      dockerfile: ./postgres.dockerfile
      context: .
    image: api-db
    container_name: api-db-container
    restart: always
    environment:
      POSTGRES_PASSWORD: mk
      POSTGRES_USER: mk
      POSTGRES_DB: mk-api
    ports:
      - '5433:5432'
    networks:
      - ist-network

networks:
  ist-network:
    driver: bridge
